[book]
authors = ["张守磊"]
language = "zh"
multilingual = false
src = "src"
title = "饮冰室"

[build]
build-dir = "book"
create-missing = true

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
smart-punctuation = true
mathjax-support = true
copy-fonts = true
no-section-label = false
git-repository-url = "https://github.com/qkunzh"
git-repository-icon = "fa-github-alt"
site-url = "/8848/"
