[book]
authors = ["张守磊"]
language = "zh"
multilingual = false
src = "src"
title = "饮冰室"

[build]
build-dir = "book"
create-missing = true

[preprocessor.katex]
after = ["links"]

[preprocessor.alerts]

[preprocessor.repl]
# iframe url, default is https://mr-addict.github.io/mdbook-repl/embed/
src = "https://mr-addict.github.io/mdbook-repl/embed/"


# python is disabled by default and loading is lazy
python.enable = true
python.loading = "lazy"

# typescript is disabled by default and loading is lazy
typescript.enable = true
typescript.loading = "lazy"

# javascript is disabled by default and loading is lazy
javascript.enable = true
javascript.loading = "lazy"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
smart-punctuation = true
mathjax-support = true
copy-fonts = true
no-section-label = false
git-repository-url = "https://github.com/qkunzh"
git-repository-icon = "fa-github-alt"
site-url = "/8848/"

